# Generated by Django 4.0.4 on 2022-05-06 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment_date_like_date_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedby', models.CharField(max_length=128)),
                ('followingto', models.CharField(max_length=128)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
