# Generated by Django 4.0.4 on 2022-05-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_follow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.CharField(default='', max_length=150),
        ),
    ]
