# Generated by Django 4.0.4 on 2022-05-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_like_like_like_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
    ]
