# Generated by Django 4.0.4 on 2022-05-09 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_post_liker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='Post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
