# Generated by Django 4.0.4 on 2022-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
