# Generated by Django 4.0.4 on 2022-04-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
    ]
