# Generated by Django 4.0.4 on 2022-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'electronics'), ('Fashion', 'fashion'), ('Furniture', 'furniture'), ('Food', 'food'), ('Toys & Hobby', 'toys & hobby'), ('Other', 'other')], max_length=30),
        ),
    ]
