# Generated by Django 4.0.4 on 2022-04-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='username',
        ),
    ]
