# Generated by Django 4.0.4 on 2022-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
